name: Delete Old Releases

on:
  workflow_dispatch: # Permet de lancer l'action manuellement depuis GitHub
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Exécute l'action tous les jours à minuit

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 1
          release-drop-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
