jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sgpublic/delete-release-action@v1.3
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
